(require 'lge-frame-hooks)

(defun fix-up-xterm-control-arrows ()
  (let ((map (if (boundp 'input-decode-map)
                 input-decode-map
               function-key-map)))
    (define-key map "\e[1;5A" [C-up])
    (define-key map "\e[1;5B" [C-down])
    (define-key map "\e[1;5C" [C-right])
    (define-key map "\e[1;5D" [C-left])
    (define-key map "\e[5A"   [C-up])
    (define-key map "\e[5B"   [C-down])
    (define-key map "\e[5C"   [C-right])
    (define-key map "\e[5D"   [C-left])

    (define-key map "O3A" [M-up])
    (define-key map "O3B" [M-down])
    (define-key map "O3C" [M-right])
    (define-key map "O3D" [M-left])
    (define-key map "O2B" [S-down])
    (define-key map "O2A" [S-up])
    (define-key map "O2D" [S-left])
    (define-key map "O2C" [S-right])
    (define-key map "O7B" [C-M-down])
    (define-key map "O7A" [C-M-up])
    (define-key map "" [C-/])
    (define-key map "\C-j" [C-<return>])
    (define-key map "[3;5~" [C-<delete>])
    ))

(add-hook 'after-make-console-frame-hooks
          (lambda ()
            (when (< emacs-major-version 23)
              (fix-up-xterm-control-arrows))
            (xterm-mouse-mode 1) ; Mouse in a terminal (Use shift to paste with middle button)
            (when (fboundp 'mwheel-install)
              (mwheel-install))))

(provide 'lge-xterm)
