#! /usr/bin/env node

require( 'shelljs/global' );

var dir = process.argv[2] || 'test';
var pkgName = JSON.parse( cat( 'component.json' ) ).name;

var comp = {
  "name": "test",
  "description": "Tests for " + pkgName,
  "dependencies": {},
  "development": {
    "lge88/expect.js": "*"
  },
  "scripts": [
    "all.js",
    "t1.js"
  ],
  "main": "all.js",
  "paths": [
    "../components",
    "../.."
  ],
  "local": [
    pkgName
  ]
};

var pkg = {
  "name": pkgName,
  "version": "0.0.1",
  "dependencies": {},
  "devDependencies": {
    "expect.js": "~0.2.0"
  },
  "main": "all.js"
};


mkdir( '-p', dir );
cd( dir );

JSON.stringify( comp, null, 2 ).to( 'component.json' );
JSON.stringify( pkg, null, 2 ).to( 'package.json' );
// exec( 'component install -d' );

'require( \'./t1.js\')'.to( 'all.js' );
[
  'var pipeline = require( \'' + pkgName + '\' ).pipeline;',
  'var expect = require( \'expect.js\' );',
  '',
  '',
  'describe( \'' + pkgName + '\', function() {',
  '',
  '  it( \'#example\', function() {',
  '    expect( 1 ).to.be( 1 );',
  '  } );',
  '',
  '} );'
].join( '\n' ).to( 't1.js' );

// exec( 'component build -d' );

[
  'node:',
  '\tNODE_PATH=.. mocha all.js',
  '',
  'browser: build',
  '\topen browser/index.html',
  '',
  'build: install',
  '\tcomponent build -d',
  '',
  'install:',
  '\tcomponent install -d',
  '',
  '.PHONY: build install'
].join( '\n' ).to( 'Makefile' );


mkdir( '-p', 'browser' );
cd( 'browser' );
exec( 'mocha init .' );
rm( 'tests.js' );

[
  '<!DOCTYPE html>',
  '<html>',
  '<head>',
  '<title>Mocha</title>',
  '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '<link rel="stylesheet" href="mocha.css" />',
  '</head>',
  '<body>',
  '<div id="mocha"></div>',
  '<script src="mocha.js"></script>',
  '<script>mocha.setup(\'bdd\')</script>',
  '<script src="../build/build.js"></script>',
  '<script>',
  'require( \'test\' );',
  'mocha.run();',
  '</script>',
  '</body>',
  '</html>'
].join( '\n' ).to( 'index.html' );

cd( '..' );
exec( 'make browser' );
