#!/usr/bin/env node

require('shelljs/global');

var path = require('path');
var dbFile = path.resolve( __dirname, '../.npm_globals.txt' );

var str = exec( 'npm ls -g --parseable --depth=0 2> /dev/null | awk -F/ \'NR>1 {print $NF}\'', { silient: true } ).output;
str.to( dbFile );
