#! /usr/bin/env node

require( 'shelljs/global' );
var path = require('path');
var rl = require( 'readline' ).createInterface( {
  input: process.stdin,
  output: process.stdout
} );

if ( process.argv.length !== 4  ) {
  echo( 'Usage: tmpl templatePath [destinationPath]' );
  exit( 1 );
}

var tmplName = process.argv[2];
var dir = process.argv[3] || 'test-' + now().join( '-' );
var tmplBaseDir = path.resolve( __dirname, '../.templates' );
var tmplDir = path.resolve( tmplBaseDir, tmplName );
var savedDir = pwd();

if ( !test( '-d', tmplDir ) ) {
  echo( 'Can\'t not find template named ' + tmplName );
  echo( 'It is supposed to be at ' + tmplDir );
  exit( 1 );
}

if ( test( '-e', dir ) ) {
  rl.question( dir + ' is already there, Override? [y/N]', function( ans ) {
    echo( 'ans:' + ans );
    if ( ans === 'y' ) {
      echo( 'OK, doit' );
      doit();
    } else {
      echo( 'Abort.' );
      exit();
    }
  } );
} else {
  doit();
}

function doit() {
  echo( 'Copy template files from ' + tmplDir );
  mkdir( '-p', dir );
  cd( dir );
  cp( '-fr', tmplDir + '/*', './' );
  cp( '-fr', tmplDir + '/.gitignore', './' );
  echo( 'Files are copied to ' + dir );

  var savedDir = pwd();

  if ( test( '-d', '_init' ) ) {
    echo( 'Run scripts under ' + dir +'_init folder' );

    var tasks = [];
    cd( '_init' );
    ls( '.' ).forEach( function( f ) {
      try {
        var task = require( path.resolve( f ) );
      } catch( err ) {
        console.log( err );
      }

      if ( typeof task.execute === 'function' ) {
        task.order || ( task.order = 0 );
        tasks.push( task );
      }
    } );

    tasks
      .sort( function( a, b ) { return a.order - b.order; } )
      .forEach( function( t ) {
        cd( savedDir );
        t.execute();
        cd( savedDir );
      } );

    echo( 'Remove _init folder' );
    rm( '-r', './_init' );

    cd( savedDir );
  }

  echo( 'Done!' );
  exit();
}
