(require-package 'google-translate)
(require 'google-translate)
(setq google-translate-default-source-language "en")
(setq google-translate-default-target-language "zh-CN")
(provide 'lge-google-translate)
